<?php
return[		
	'ListItem',
	'text'=>'序号',
	'attr_style'=>'min-width:80px;',
	[
		[
			'number',
			'name'=>'ordernum',	
			'text'=>'序号',
			'attr_style'=>'width:80px;',
			'attr_class'=>'form-control',
		],
	],	
];