<?php
return [
    'js'=>[
        'admin-layout-js'=>[
            'bootstrap/dist/js/bootstrap.bundle.js',
            'overlayscrollbars/browser/overlayscrollbars.browser.es5.js',
            'xq-admin-layout/dist/js/xq-admin-layout.js',
        ],
        'admin-page-js'=>[
            'bootstrap/dist/js/bootstrap.bundle.js',
            'xq-admin-page/dist/js/xq-admin-page.js',
        ],
        'admin-treegrid-js'=>[
            'bootstrap/dist/js/bootstrap.bundle.js',
            'xq-treegrid/dist/js/xq-treegrid.js',
        ],
    ],
    'css'=>[
        'admin-layout-css'=>[
            'bootstrap/dist/css/bootstrap.css',
            'bootstrap-icons/font/bootstrap-icons.css',
            'overlayscrollbars/styles/overlayscrollbars.css',
            'xq-admin-layout/dist/css/xq-admin-layout.css',
        ],
        'admin-page-css'=>[
            'bootstrap/dist/css/bootstrap.css',
            'bootstrap-icons/font/bootstrap-icons.css',
            'xq-admin-page/dist/css/xq-admin-page.css',
        ],
        'admin-treegrid-css'=>[
            'bootstrap/dist/css/bootstrap.css',
            'bootstrap-icons/font/bootstrap-icons.css',
            'xq-treegrid/dist/css/xq-treegrid.css',
        ]
    ]
];